<?php $__env->startSection('content'); ?>
<div class="container mx-auto px-4 py-8 bg-gray-50/50">
    <div class="max-w-5xl mx-auto">
        <h2 class="text-2xl font-extrabold text-brand-dark mb-6">Test Reports</h2>
        
        <div class="bg-white rounded-xl border border-gray-200 p-12 shadow-sm text-center">
            <div class="w-24 h-24 bg-brand-light/20 text-brand-secondary rounded-full flex items-center justify-center text-4xl mx-auto mb-6">
                <i class="far fa-file-alt"></i>
            </div>
            <h3 class="font-extrabold text-gray-900 text-xl mb-2">Reports Coming Soon</h3>
            <p class="text-gray-500 font-semibold mb-6 max-w-md mx-auto">Your test reports will be displayed here once they are generated by the laboratory.</p>
            
            <button class="bg-brand-dark text-white px-6 py-3 rounded-xl font-bold text-sm hover:bg-brand-secondary transition shadow-sm">
                Book a New Test
            </button>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\lab\lab\resources\views/patient/reports.blade.php ENDPATH**/ ?>